import jsPDF from 'jspdf';

interface PDFGeneratorOptions {
  userName: string;
  originalImage: string;
  tracedImage: string;
  date: Date;
}

export async function generatePDF(options: PDFGeneratorOptions): Promise<jsPDF> {
  const { userName, originalImage, tracedImage, date } = options;
  
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  
  // Colors
  const primaryColor: [number, number, number] = [20, 145, 135]; // Teal
  const textColor: [number, number, number] = [30, 30, 40];
  const mutedColor: [number, number, number] = [120, 120, 130];
  
  // Header with gradient effect (simulated)
  pdf.setFillColor(...primaryColor);
  pdf.rect(0, 0, pageWidth, 45, 'F');
  
  // Logo/Title
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(24);
  pdf.setFont('helvetica', 'bold');
  pdf.text('BioTrace', 20, 22);
  
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.text('Fingerprint Analysis Report', 20, 32);
  
  // Date on the right
  pdf.setFontSize(10);
  pdf.text(date.toLocaleDateString('en-US', { 
    year: 'numeric', 
    month: 'long', 
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  }), pageWidth - 20, 22, { align: 'right' });
  
  // User info section
  pdf.setTextColor(...textColor);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Analysis Details', 20, 60);
  
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(...mutedColor);
  pdf.text('Subject Name:', 20, 72);
  pdf.setTextColor(...textColor);
  pdf.text(userName, 55, 72);
  
  pdf.setTextColor(...mutedColor);
  pdf.text('Report ID:', 20, 80);
  pdf.setTextColor(...textColor);
  pdf.text(`BT-${Date.now().toString(36).toUpperCase()}`, 55, 80);
  
  // Divider
  pdf.setDrawColor(200, 200, 210);
  pdf.line(20, 88, pageWidth - 20, 88);
  
  // Images section
  pdf.setTextColor(...textColor);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Image Comparison', 20, 100);
  
  const imgWidth = 75;
  const imgHeight = 75;
  const imgY = 108;
  
  // Original image
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(...mutedColor);
  pdf.text('Original Image', 20, imgY);
  
  try {
    pdf.addImage(originalImage, 'PNG', 20, imgY + 4, imgWidth, imgHeight);
  } catch (e) {
    pdf.setFillColor(240, 240, 245);
    pdf.rect(20, imgY + 4, imgWidth, imgHeight, 'F');
    pdf.text('Image not available', 40, imgY + 40);
  }
  
  // Traced image
  pdf.text('Traced Fingerprint', pageWidth / 2 + 5, imgY);
  
  try {
    pdf.addImage(tracedImage, 'PNG', pageWidth / 2 + 5, imgY + 4, imgWidth, imgHeight);
  } catch (e) {
    pdf.setFillColor(240, 240, 245);
    pdf.rect(pageWidth / 2 + 5, imgY + 4, imgWidth, imgHeight, 'F');
    pdf.text('Image not available', pageWidth / 2 + 25, imgY + 40);
  }
  
  // Processing info
  const infoY = imgY + imgHeight + 20;
  pdf.setTextColor(...textColor);
  pdf.setFontSize(14);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Processing Pipeline', 20, infoY);
  
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(...mutedColor);
  
  const steps = [
    '1. Grayscale conversion',
    '2. Gaussian blur (noise reduction)',
    '3. Contrast enhancement (CLAHE)',
    '4. Sobel edge detection',
    '5. Morphological operations',
    '6. Ridge pattern extraction'
  ];
  
  steps.forEach((step, index) => {
    pdf.text(step, 25, infoY + 8 + (index * 6));
  });
  
  // Watermark
  pdf.setFontSize(10);
  pdf.setTextColor(180, 180, 190);
  pdf.text('Hackathon Demo Project', pageWidth / 2, pageHeight - 20, { align: 'center' });
  
  // Footer
  pdf.setDrawColor(200, 200, 210);
  pdf.line(20, pageHeight - 25, pageWidth - 20, pageHeight - 25);
  
  pdf.setFontSize(8);
  pdf.text('Generated by BioTrace - Fingerprint Tracing Application', pageWidth / 2, pageHeight - 10, { align: 'center' });
  
  return pdf;
}
